### ISSUE TITLE
Hacktoberfest - P.O.G.

### ISSUE THREAD

**Issue by luanjpb** [LU4LII/my_tools#1]

**Comment by adamo57** [comment]
What does P.O.G. mean?

**Comment by luanjpb** [comment]
Sorry my bad English.
It is a Brazilian slang that means oriented programming "gambiarra".
"gambiarra" is to solve a problem with something unexpected, because of lack of time or patience.
I'll add some P.O.G’s that develops over the years in this repository. Please contribute.

**Comment by essankov** [comment]
Where is the issues you need help with?

**Comment by Cereal84** [comment]
I've send a pull request about the "issue", can you check if my assumption (about the issue) was right ?
